78 ajustar layout do site de acordo com o novo prototipo
saibrotech/mentorship-backend pull request #87
Opened 2022-12-14 11:09 UTC by gutivalente

2022-12-14 15:03 UTC, isabelahyeda commented on job/static/job/js/job.js
> +                <i class="bi ${AREA_ICON[job.category.code]} icon bg-secondary text-white rounded-circle border"></i> \
Retirei o border, parece não ser necessário.

2022-12-14 15:04 UTC, isabelahyeda commented on job/static/job/js/job.js
> +                <i class="bi ${AREA_ICON[job.category.code]} icon bg-secondary text-white rounded-circle border"></i> \
dá para retirar o border, parece não ser necessário

2022-12-14 15:08 UTC, isabelahyeda commented on job/static/job/js/job.js
> +        <div class="d-flex align-items-center mt-2 mt-sm-0"> \
Aqui tb acredito não ser necessário aplicar margin (mt-2 mt-sm-0)

2022-12-14 15:29 UTC, isabelahyeda requested changes

2022-12-14 15:29 UTC, isabelahyeda commented on job/templates/job/job_detail.html
>      <main class="container px-4 py-5">
Sugiro remover o padding do container (px-4, py-5), fica melhor sem em telas menores.

2022-12-14 15:29 UTC, isabelahyeda commented on job/templatetags/job_tags.py
> +    border"></i>
Aqui tb dá para remover o border, seguindo o raciocínio anterior.

2022-12-14 15:29 UTC, isabelahyeda commented on static/css/styles.css
> +
O efeito hover não funcionou. Sugestão de código:

.icon:hover {
    background-color: #0086FF;
}

.icon-link:hover {
    text-decoration: none;
}

<a **class="icon-link"** href="?area={{area.code}}">
                <div class="d-flex justify-content-center mt-4">
                    {{area.code | area_icon:chosen_area}}
                </div>
                <div class="d-flex justify-content-center pt-2">
                    <span class="text-white">{{area.name}}</span>
                </div>
            </a>

2022-12-15 12:21 UTC, piantino commented on job/static/job/js/job.js
> +        <div class="d-flex align-items-center mt-2 mt-sm-0"> \
Necessário no mobile, retirei do primeiro botão de detalhes:

![image](https://user-images.githubusercontent.com/737364/207858092-8f97e297-28d7-4e50-8a37-2d77a772906f.png)

2022-12-15 12:22 UTC, piantino commented on job/templatetags/job_tags.py
> +    border"></i>
Mesma questão de https://github.com/saibrotech/mentorship-backend/pull/87#discussion_r1049572549

2022-12-15 12:29 UTC, piantino commented on job/templates/job/job_detail.html
>      <main class="container px-4 py-5">
Classes removidas com sugerido.

2022-12-15 12:29 UTC, piantino commented on static/css/styles.css
> +
O efeito está funcionando, acho que foi problema de cache =)

2022-12-15 12:32 UTC, isabelahyeda commented on job/static/job/js/job.js
> +                <i class="bi ${AREA_ICON[job.category.code]} icon bg-secondary text-white rounded-circle border"></i> \
Obrigada pela experiência, coisas que não percebi, foi muito educativo.

2022-12-15 12:33 UTC, isabelahyeda approved these changes

2022-12-15 12:33 UTC, merged

2022-12-15 12:35 UTC, isabelahyeda commented on job/static/job/js/job.js
> +        <div class="d-flex align-items-center mt-2 mt-sm-0"> \
Verdade. Foi até uma sugestão minha e não tinha lembrado.